### ISSUE TITLE
Feature Request: Giveaway

### ISSUE THREAD

**Issue by Wolfsterror** [PakL/TTVStreamerTool#13]
Is it possible to integrate a function for Giveaways? 
It would be nice if you can exclude or add different users from the giveaway. For example: Giveaway only for subscribtions or for followers. Possibly Timing how long people have to follow the channel.
It would also be nice if there were different types of giveaways. For example by active users who have written something within a period or by a keyword.

**Comment by PakL** [comment]
Now completly possible via the chatbot addon.
Check out this example: https://github.com/PakL/ttvst-chatbot/wiki/Giveaway-command
