### ISSUE TITLE
Feature Eequest: include Spotify to music overlay

### ISSUE THREAD

**Issue by JFFSirlanz** [PakL/TTVStreamerTool#16]
would it be possible to includ spotify playlists or in generel Spotify to the music overlay?

**Comment by PakL** [comment]
A short investigation leaves me to believe that this should be possible via the Spotify Web API.
https://developer.spotify.com/documentation/web-api/reference/player/get-information-about-the-users-current-playback/

There's just the problem of the legality. I would recommend using https://www.pretzel.rocks instead. It can also output the playing track into a file.

**Comment by PakL** [comment]
Since this feature would be not worth the work it'll take I decided not to implement it. pretzel has everything you need and is a legally currated, better alternative.
