### ISSUE TITLE
Logo Design Offering as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [PakL/TTVStreamerTool#17]
Hello Sir. I'm a Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks for the attention.

**Comment by PakL** [comment]
Hello Mr. Ismail,
that is a very nice offer I'd be willing to accept under a few conditions:
* I cannot offer any compensation in any form
* The logo would be packed as part of the software under the MIT licence, meaning that everyone would be allowed to copy, modify and distribute that logo freely

Best regards!

**Comment by anharismail** [comment]
Hello @PakL Sir.

I've designed a logo for this project. This logo concept inspired from chat (forum) idea and Media Player (streaming) idea. Very welcome if you have any opinions or suggestions about it.

Regards.

![TTVStreamerTool Ver  1](https://user-images.githubusercontent.com/37614260/60878051-366eaf00-a269-11e9-8798-7a1cd7194423.png)

**Comment by PakL** [comment]
Hey @anharismail,
I like the logo very much but see an issue on a smaller scale. Since the upper left application icon on windows has a standard size of 16x16px. The logo in at that scale might not work that well (see screenshot below).
![logosmall](https://user-images.githubusercontent.com/966377/60904103-c2390900-a272-11e9-9702-021796c52b14.png)
Maybe you have a suggestion how to solve this.

**Comment by anharismail** [comment]
Hi @PakL Sir. Thanks for your opinions about it.

I've just tried to fix it. I try to make it bigger and more simple in similar version.

![TTVStreamerTool Ver  2](https://user-images.githubusercontent.com/37614260/60943839-65d8f680-a311-11e9-806c-70011c5b5596.png)

**Comment by PakL** [comment]
Yes, that will work better as an icon for the application.
Although, I would like to use both. The first one for promotional stuff and a new splash screen and the second one purely as an icon.

That leaves us with how you want to share your work. You could make a pull request and put them in a subfolder under `/res/`. However I would like a bigger version or a project file/svg so I can better resample it later, if necessary.

**Comment by anharismail** [comment]
Thanks for your response. As you said, I have made a pull request about it.

and I also provide all editable files for your access, here: https://drive.google.com/drive/u/1/folders/1vMGAFYjRDxh1f7XBmuJRnBHhuG3xbNYa

**Comment by PakL** [comment]
Awesome. Merged the pull request.
Thank you very much for you great work.
