### ISSUE TITLE
Scaling issue for Stream opening

### ISSUE THREAD

**Issue by Wolfsterror** [PakL/TTVStreamerTool#18]
Hey,
thanks for the new Minor Updates! Found an issue with the Button "Hier klicken zum Stream anschauen". The Button is compressed since Minor 0.9.0 and now the text goes down into the chat.
![grafik](https://user-images.githubusercontent.com/1077983/56382304-5f0d7c80-6217-11e9-9b00-1c1a06be10d4.png)

**Comment by PakL** [comment]
Double clicking the scaling bar should fix it. I will investigate further, why this happend in the first place...

**Comment by PakL** [comment]
Should no longer be an issue with an upcoming patch (8b4c4f47fdc52f1678db929c7fbab8749b5313c7)
