### ISSUE TITLE
[BUG] Crash when opening Creator-Dashboard from Moderation view

### ISSUE THREAD

**Issue by Wolfsterror** [PakL/TTVStreamerTool#26]
**Describe the bug**
When I open my mod view in TTVST, it gives me the opportunity to open the creator dashboard. A pop-up also appears briefly, it remains white and the entire tool crashes. Unfortunately there are no logs. 

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Creator-Dashboard'

**Expected behavior**
The twitch Creator dashboard should open in a new window.

**Environment (please complete the following information):**
 - OS: [Win 10 x64]
 - Tool Version [2.0.0 rc.1]

**Comment by PakL** [comment]
As a fix (for now) windows that would normally open as a tab will open inside the current view.
Update dashboard addon for it to take effect.
